#!/bin/bash
chmod +x install
./install
sudo apt remove gnome-games ubiquity-frontend-gtk
sudo apt autoremove

mkdir /tmp/full-install

cp full-install.zip /tmp/full-install
cd /tmp/full-install

unzip full-install.zip

sudo cp -f issue /etc
sudo cp -f os-release /usr/lib/
sudo cp -f watermark.png /usr/share/plymouth/themes/spinner/watermark.png
sudo cp -f watermark.png /usr/share/plymouth/ubuntu-logo.png

sudo update-initramfs -u
sudo update-grub

cd /tmp
rm -f -r full-install
