#!/bin/bash
echo running install
chmod +x install
./install
echo removing extra packages
sudo apt remove gnome-games light-locker systemback
sudo apt autoremove
echo setting up tmp
tmp=/tmp/full-install

mkdir $tmp

cp -f -r full-install-files/* $tmp
cd $tmp

echo setting system info
sudo cp -f $tmp/issue /etc
echo setting boot screen
sudo apt install plymouth-themes
sudo update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/spinner/spinner.plymouth 100
sudo cp -f $tmp/watermark.png /usr/share/plymouth/themes/spinner/watermark.png
sudo cp -f $tmp/watermark.png /usr/share/plymouth/ubuntu-logo.png
sudo update-initramfs -u
sudo update-grub

echo cleaning up
sudo rm -f -r $tmp
