#!/bin/bash
echo installing packages
sudo add-apt-repository ppa:xuzhen666/dockbarx #dockbarx ppa
sudo apt install $(cat packages)

echo setting up tmp

tmp=/tmp/Rinstall

mkdir $tmp

echo copying files to tmp...
cp -r -f * $tmp
cd $tmp
echo setting up $HOME

cp -r -f $tmp/install-files/config $HOME/.config 

echo creating default user
sudo cp -r -f $tmp/install-files/.config /etc/skel/
sudo cp -r -f $tmp/install-files/.bashrc /etc/skel/
sudo cp -r -f /etc/skel/* /usr/share/lightdm/guest-session/skel

chmod +x $tmp/RawsonlinuxScripts/*
sudo cp -f -r $tmp/RawsonlinuxScripts/* /usr/bin
cd
echo configuring lightdm
sudo cp -r -f $tmp/install-files/lightdm.conf.d /usr/share/lightdm/lightdm.conf.d

echo cleaning up...
sudo rm -r -f $tmp
cd $PWD 

