#!/bin/bash
chmod +x install
./install
sudo apt remove gnome-games ubiquity-gtk-frontend 
sudo apt autoremove

mkdir /tmp/updates

cp updates.zip /tmp/updates
cd /tmp/updates

unzip updates.zip

sudo cp -f issue /etc
sudo cp -f os-release /usr/lib/
sudo cp -f watermark.png /usr/share/plymouth/themes/spinner/watermark.png
sudo cp -f watermark.png /usr/share/plymouth/ubuntu-logo.png

sudo update-initramfs -u

cd /tmp
rm -f -r updates
